### ISSUE TITLE
Python3 compatible release

### ISSUE THREAD

**Issue by petschki** [plone/plone.recipe.haproxy#5]

**Comment by ale-rt** [comment]
Hi, I have no power to release it.
Trying to ping the maintainers I see on https://pypi.org/project/plone.recipe.haproxy: @aclark4life, @fschulze, @hannosch, @mjpieters, @tesdal, @wichert, @witsch

**Comment by aclark4life** [comment]
Pong. I can take a look if no one else gets to it before me.

**Comment by daniele-andreotti** [comment]
Hi,

any news for this?
@aclark4life

**Comment by wichert** [comment]
I haven't been involved in any Plone for a few years now. I can give someone access to make a release if needed.

**Comment by ale-rt** [comment]
@wichert you are a savior :)
If you want please add me (`alert`) and the I would also probably add the `collective` user.

**Comment by wichert** [comment]
Done!

**Comment by ale-rt** [comment]
Thanks! I will release in the afternoon :)

**Comment by ale-rt** [comment]
I made a 2.0rc1 release https://pypi.org/project/plone.recipe.haproxy/2.0rc1/
Please @petschki, @daniele-andreotti and whoever is interested try that out and report your feedback.
If everything is good I will make a 2.0 final.

**Comment by petschki** [comment]
I've just testet 2.0rc1 in production and works perfectly! I'd say: ready for final 👍

**Comment by ale-rt** [comment]
Thanks a lot for your feedback guys!
I released https://pypi.org/project/plone.recipe.haproxy/#history :)
